# test_assets.gd — work order 07: M8Assets manifest resolution (key match,
# aliases, absent/malformed manifest), runtime texture loading + cache,
# icon class-gating, and the sprite_sheet frame-box contract (4 facing rows
# down/left/right/up x 4 cols, frame box = image_size/4) against a synthetic
# fixture sheet generated by the test itself. All fixture files are written
# (and removed) by the test; no dependency on real assets existing.
extends RefCounted

const T := preload("res://tests/unit/_t.gd")
const AssetsScript := preload("res://autoload/m8_assets.gd")

const FIX_DIR := "user://m8fixtures_wo07"
const MANIFEST := FIX_DIR + "/manifest.json"

var _nodes: Array = []
var _files: Array = []

func cleanup() -> void:
	for f in _files:
		DirAccess.remove_absolute(ProjectSettings.globalize_path(f))
	DirAccess.remove_absolute(ProjectSettings.globalize_path(FIX_DIR))
	for n in _nodes:
		n.free()

# ------------------------------------------------------------- fixtures

func _write(path: String, text: String) -> void:
	var f := FileAccess.open(path, FileAccess.WRITE)
	f.store_string(text)
	f.close()
	_files.append(path)

func _write_png(path: String, w: int, h: int) -> void:
	var img := Image.create_empty(w, h, false, Image.FORMAT_RGBA8)
	img.fill(Color(0.8, 0.5, 0.2, 1.0))
	img.save_png(path)
	_files.append(path)

# Fixture manifest exercising every resolution shape the loader supports.
func _fixture_assets() -> Node:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(FIX_DIR))
	_write_png(FIX_DIR + "/fx_icon.png", 8, 8)
	_write_png(FIX_DIR + "/fx_sheet.png", 64, 96)  # frame box 16x24
	var entries := [
		{"key": "fx_icon", "class": "item_icon", "file": FIX_DIR + "/fx_icon.png",
			"aliases": ["icon_fixture_alpha", "icon_fixture_beta"]},
		{"key": "fx_sheet", "class": "sprite_sheet", "file": FIX_DIR + "/fx_sheet.png",
			"aliases": ["chr_fixture", "fx_icon"]},  # alias shadowing a real key
		{"key": "fx_icon_gone", "class": "item_icon", "file": FIX_DIR + "/nope.png"},
		{"key": "music.fixture", "class": "bgm", "file": FIX_DIR + "/fx_bgm.mp3",
			"aliases": ["bgm_fixture_alias"]},
		{"key": "music.gone", "class": "bgm", "file": FIX_DIR + "/nope.mp3"},
	]
	_write(MANIFEST, JSON.stringify({"assets": entries}))
	var a: Node = AssetsScript.new()
	a.load_manifest(MANIFEST)
	_nodes.append(a)
	return a

# ------------------------------------------------------------ resolution

func test_absent_manifest_is_empty() -> void:
	var a: Node = AssetsScript.new()
	_nodes.append(a)
	a.load_manifest(FIX_DIR + "/does_not_exist.json")
	T.ok(not a.manifest_loaded, "absent manifest -> not loaded")
	T.eq(a.entries.size(), 0, "absent manifest -> zero entries")
	T.eq(a.resolve("anything"), null, "resolve is null on empty manifest")
	T.eq(a.icon_texture("anything"), null, "icon_texture null on empty manifest")
	T.eq(a.sheet("anything"), {}, "sheet {} on empty manifest")

func test_malformed_manifest_degrades_to_empty() -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(FIX_DIR))
	_write(FIX_DIR + "/bad_manifest.json", "{ not json ]")
	var a: Node = AssetsScript.new()
	_nodes.append(a)
	a.load_manifest(FIX_DIR + "/bad_manifest.json")
	T.ok(not a.manifest_loaded, "malformed manifest -> not loaded")
	T.eq(a.resolve("anything"), null, "resolve null on malformed manifest")

func test_resolve_by_key() -> void:
	var a := _fixture_assets()
	T.ok(a.manifest_loaded, "fixture manifest loads")
	var r: Variant = a.resolve("fx_icon")
	T.ok(r != null, "key match resolves")
	T.eq(r["key"], "fx_icon", "resolved manifest key")
	T.eq(r["class"], "item_icon", "resolved class")
	T.eq(r["path"], FIX_DIR + "/fx_icon.png", "user:// fixture path passes through")
	T.eq(a.resolve("fx_unknown"), null, "unknown key -> null (placeholder)")

func test_resolve_by_alias() -> void:
	var a := _fixture_assets()
	var r: Variant = a.resolve("icon_fixture_alpha")
	T.ok(r != null, "alias resolves")
	T.eq(r["key"], "fx_icon", "alias maps to owning manifest key")
	T.eq(a.resolve("icon_fixture_beta")["key"], "fx_icon", "every alias in the array resolves")
	T.eq(a.resolve("chr_fixture")["key"], "fx_sheet", "sheet alias resolves")
	# direct key match wins over another entry's alias of the same name
	T.eq(a.resolve("fx_icon")["key"], "fx_icon", "key match takes precedence over alias")

func test_game_relative_paths_map_to_res() -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(FIX_DIR))
	_write(FIX_DIR + "/rel_manifest.json", JSON.stringify({"assets":
			[{"key": "fx_rel", "class": "item_icon", "file": "assets/icons/x.png"}]}))
	var a: Node = AssetsScript.new()
	_nodes.append(a)
	a.load_manifest(FIX_DIR + "/rel_manifest.json")
	T.eq(a.resolve("fx_rel")["path"], "res://assets/icons/x.png",
			"game-dir-relative file lands under res:// via the src/assets symlink")

# -------------------------------------------------------------- textures

func test_icon_texture_loads_and_caches() -> void:
	var a := _fixture_assets()
	var tex: Texture2D = a.icon_texture("icon_fixture_alpha")
	T.ok(tex != null, "icon texture loads at runtime")
	T.eq(tex.get_width(), 8, "icon width")
	T.eq(tex.get_height(), 8, "icon height")
	T.ok(a.icon_texture("fx_icon") == tex, "texture cached per manifest key (same instance)")

func test_icon_texture_soft_fails() -> void:
	var a := _fixture_assets()
	T.eq(a.icon_texture(""), null, "empty sprite key -> null")
	T.eq(a.icon_texture("icon_never_generated"), null, "unresolved key -> null")
	T.eq(a.icon_texture("music.fixture"), null, "non-icon class -> null (class-gated)")
	T.eq(a.icon_texture("fx_icon_gone"), null, "manifest entry with missing file -> null")

# ----------------------------------------------------------- walk sheets

func test_sheet_frame_box() -> void:
	var a := _fixture_assets()
	var s: Dictionary = a.sheet("chr_fixture")
	T.ok(not s.is_empty(), "sprite_sheet class resolves to a sheet")
	T.eq(s["frame_w"], 16, "frame box width = image_w / 4")
	T.eq(s["frame_h"], 24, "frame box height = image_h / 4")
	T.eq(s["texture"].get_width(), 64, "sheet texture loads full-size")
	T.eq(a.sheet("fx_icon"), {}, "non-sheet class -> {} (class-gated)")
	T.eq(a.sheet("chr_never_generated"), {}, "unresolved key -> {}")
	T.eq(a.sheet(""), {}, "empty key -> {}")

func test_sheet_region_rows_and_cycle() -> void:
	var a := _fixture_assets()
	var s: Dictionary = a.sheet("chr_fixture")
	# rows in fixed facing order: down / left / right / up
	T.eq(a.sheet_region(s, "down", 0), Rect2(0, 0, 16, 24), "down = row 0, frame 0 = col 0")
	T.eq(a.sheet_region(s, "left", 2), Rect2(32, 24, 16, 24), "left = row 1")
	T.eq(a.sheet_region(s, "right", 3), Rect2(48, 48, 16, 24), "right = row 2")
	T.eq(a.sheet_region(s, "up", 1), Rect2(16, 72, 16, 24), "up = row 3")
	# 4-frame walk cycle wraps by modulo; junk facing clamps to row 0
	T.eq(a.sheet_region(s, "down", 5), Rect2(16, 0, 16, 24), "frame index wraps mod 4")
	T.eq(a.sheet_region(s, "sideways", 0), Rect2(0, 0, 16, 24), "unknown facing -> row 0")

# ---------------------------------------------------------- real manifest

# The real manifest (when present) must parse and self-resolve; iterates
# entries so no content/asset ids are hardcoded here.
func test_real_manifest_parses() -> void:
	if not FileAccess.file_exists("res://assets/manifest.json"):
		return  # assets are progressive enhancement — absent is a valid state
	var a: Node = AssetsScript.new()
	_nodes.append(a)
	a.load_manifest("res://assets/manifest.json")
	T.ok(a.manifest_loaded, "real manifest parses")
	for key in a.entries:
		var r: Variant = a.resolve(key)
		T.ok(r != null, "manifest key self-resolves: " + str(key))
		T.ok(str(r["class"]) != "", "entry has a class: " + str(key))
		T.ok(str(r["path"]).begins_with("res://"), "entry file is game-dir-relative: " + str(key))
